// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/book/:id": {
    params: {
      "id": string;
    };
  };
  "/book/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/book-new": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/book/:id" | "/book/:id/edit" | "/book-new";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/" | "/book/:id" | "/book/:id/edit" | "/book-new";
  };
  "routes/books-list.tsx": {
    id: "routes/books-list";
    page: "/";
  };
  "routes/book-detail.tsx": {
    id: "routes/book-detail";
    page: "/book/:id";
  };
  "routes/book-edit.tsx": {
    id: "routes/book-edit";
    page: "/book/:id/edit";
  };
  "routes/book-new.tsx": {
    id: "routes/book-new";
    page: "/book-new";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/books-list": typeof import("./app/routes/books-list.tsx");
  "routes/book-detail": typeof import("./app/routes/book-detail.tsx");
  "routes/book-edit": typeof import("./app/routes/book-edit.tsx");
  "routes/book-new": typeof import("./app/routes/book-new.tsx");
};