services:
  web:
    image: daw/marvel-pop:1.0.0
    ports:
      - "8443:8443"
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/marvelpop
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=marvelpop
